export const emojiList = [
    { name: '基础_咧嘴笑', className: 'base-liezuixiao' },
    { name: '基础_墨镜', className: 'base-mojing' },
    { name: '基础_难受', className: 'base-nanshou' },
    { name: '基础_平淡', className: 'base-pingdan' },
    { name: '基础_亲吻', className: 'base-qinwen' },
    { name: '基础_伤心', className: 'base-shangxin' },
    { name: '基础_生气', className: 'base-shengqi' },
    { name: '基础_叹气', className: 'base-tanqi' },
    { name: '基础_微笑', className: 'base-weixiao' },
    { name: '基础_无表情', className: 'base-wubiaoqing' },
    { name: '基础_嘻嘻', className: 'base-xixi' },
    { name: '基础_喜欢', className: 'base-xihuan' },
    { name: '基础_笑哭', className: 'base-xiaoku' },
    { name: '基础_悲伤', className: 'base-beishang' },
    { name: '基础_馋嘴', className: 'base-chanzui' },
    { name: '基础_大哭', className: 'base-daku' },
    { name: '基础_调皮', className: 'base-tiaopi' },
    { name: '基础_愤怒', className: 'base-fennu' },
    { name: '基础_尬笑', className: 'base-gaxiao' },
    { name: '基础_鬼脸', className: 'base-guilian' },
    { name: '基础_哈哈', className: 'base-haha' },
    { name: '基础_害怕', className: 'base-haipa' },
    { name: '基础_恐怖', className: 'base-kongbu' },
    { name: '基础_困', className: 'base-kun' },
    { name: '基础_冷汗', className: 'base-lenghan' },
    { name: '基础_脸红', className: 'base-lianhong' },
]